production:
  adapter: postgresql
  url: postgres://localhost:5432/chat_production

development:
  adapter: postgresql
  url: postgres://localhost:5432/chat_development

test:
  adapter: postgresql
  url: postgres://localhost:5432/chat_test
